[build]
  command = "npm run build"
  publish = "dist/manex-ds-copilot/browser"

[build.environment]
  NODE_VERSION = "18"

# SPA Routing Configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"